  spring:
    datasource:
      driver-class-name: org.postgresql.Driver
      url: jdbc:postgresql://localhost:5432/alishev
      username: postgres
      password: root

  liquibase:
    change-log: classpath:resources/db/changelog/db.changelog-master.yaml




